### PR TITLE
Convert DS_ASSERT to UT_ASSERT instead of assert function

### LINKED ISSUE #119: Bug: Convert DS_ASSERT to UT_ASSERT instead of assert function
### Problem/Opportunity

HDMI CEC L3 is using assert function which terminates the test if the validation fails.

https://github.com/search?q=repo%3Ardkcentral%2Frdk-halif-test-hdmi_cec%20assert&type=code

Solution:

Use UT_ASSERT instead of assert function.

### Steps to reproduce

Run VTS with run all option.

### Expected Behavior

All tests should run w/o crashing.

### Actual Behavior

Test crashes when the validation fails.

### Notes (Optional)

_No response_

### PR DESCRIPTION
**Pull request by KarthikeyanR470**
HDMI CEC L3 is using assert function which terminates the test if the validation fails.

https://github.com/search?q=repo%3Ardkcentral%2Frdk-halif-test-hdmi_cec%20assert&type=code

Solution:

Use UT_ASSERT instead of assert function.

### CODE REVIEW

**Review by kanjoe24 — COMMENTED** [review]
consider checking copilot review.
With introduction of UT_ASSERT, the whole logic will shift.
From the way it has been written looks like, they called assert with the intention to break whenever there is failure. Which means on failure, it will not proceed with incorrect values.
But with UT_ASSERT*, test will proceed further even when it fails. So, we need to be defensive now and re-think logic wherever necessary.

File: src/test_l3_hdmi_cec_driver.c [hunk 1]
```diff
@@ -567,8 +593,8 @@ void test_l3_hdmi_cec_hal_GetLogicalAddress(void)
     UT_LOG_INFO("Calling HdmiCecGetLogicalAddress(IN:handle:[0x%0X], OUT:logicalAddress:[])", gHandle);
     status = HdmiCecGetLogicalAddress(gHandle, &logicalAddress);
     UT_LOG_INFO("Result HdmiCecGetLogicalAddress(IN:handle:[0x%0X], OUT:logicalAddress:[%x]) HDMI_CEC_STATUS:[%s])", gHandle, logicalAddress, UT_Control_GetMapString(cecError_mapTable,status));
-    assert(status == HDMI_CEC_IO_SUCCESS);
-    assert(logicalAddress >= 0 && logicalAddress <= 15);
+    UT_ASSERT_EQUAL(status, HDMI_CEC_IO_SUCCESS);
```
Comment (kanjoe24) [inline src/test_l3_hdmi_cec_driver.c:600]: what happens when status != HDMI_CEC_IO_SUCCESS ? 
We don't seem to be handling that.

File: src/test_l3_hdmi_cec_driver.c [hunk 2]
```diff
@@ -648,7 +674,7 @@ void test_l3_hdmi_cec_hal_TransmitHdmiCecCommand(void) {
     UT_LOG_INFO("Calling HdmiCecTx(IN:handle:[0x%0X], IN:buf:[%p], IN:len:[%d], OUT:result:[])", gHandle, buf, len);
     int32_t status = HdmiCecTx(gHandle, buf, len, &result);
     UT_LOG_INFO("Result HdmiCecTx(IN:handle:[0x%0X], IN:buf:[%p], IN:len:[%d], OUT:result:[%s]) HDMI_CEC_STATUS:[%s]", gHandle, buf, len, UT_Control_GetMapString(cecError_mapTable, result)? UT_Control_GetMapString(cecError_mapTable, result):"HDMI_CEC_IO_SENT_FAILED", UT_Control_GetMapString(cecError_mapTable,status));
-    assert(status == HDMI_CEC_IO_SUCCESS || status == HDMI_CEC_IO_SENT_AND_ACKD || status == HDMI_CEC_IO_SENT_BUT_NOT_ACKD );
+    UT_ASSERT_TRUE(status == HDMI_CEC_IO_SUCCESS || status == HDMI_CEC_IO_SENT_AND_ACKD || status == HDMI_CEC_IO_SENT_BUT_NOT_ACKD );
```
Comment (kanjoe24) [inline src/test_l3_hdmi_cec_driver.c:707]: yes, I agree with copilot here.

File: src/test_l3_hdmi_cec_driver.c [hunk 3]
```diff
@@ -716,14 +751,27 @@ void test_l3_hdmi_cec_hal_RemoveLogicalAddress(void)
...
+    UT_ASSERT_EQUAL(status, HDMI_CEC_IO_SUCCESS);
 
-    gLogicalAddress = -1;
+    if (status == HDMI_CEC_IO_SUCCESS)
+    {
+        gLogicalAddress = -1;
+    }
+    else
+    {
+        UT_LOG_ERROR("HdmiCecRemoveLogicalAddress failed. State not updated.");
```
Comment (kanjoe24) [inline src/test_l3_hdmi_cec_driver.c]: shouldn't we return here??

File: src/test_l3_hdmi_cec_driver.c [hunk 4]
```diff
@@ -454,23 +454,33 @@ void test_l3_hdmi_cec_hal_Init(void)
     UT_LOG_INFO("Calling HdmiCecOpen(OUT:handle:[])");
     status = HdmiCecOpen(&gHandle);
     UT_LOG_INFO("Result HdmiCecOpen(OUT:handle:[0x%0X]) HDMI_CEC_STATUS:[%s]",gHandle, UT_Control_GetMapString(cecError_mapTable,status));
-    assert(status == HDMI_CEC_IO_SUCCESS);
-    assert(gHandle != 0);
+    UT_ASSERT_EQUAL_FATAL(status, HDMI_CEC_IO_SUCCESS);
+    UT_ASSERT_NOT_EQUAL(gHandle, 0);
```
Comment (kanjoe24) [inline src/test_l3_hdmi_cec_driver.c]: what happens when gHandle is 0 ?

File: src/test_l3_hdmi_cec_driver.c [hunk 5]
```diff
@@ -454,23 +454,33 @@ void test_l3_hdmi_cec_hal_Init(void)
...
+    {
+        gPhysicalAddressBytes = (uint8_t*)&gPhysicalAddress;
+
+        UT_LOG_INFO("Result HdmiCecGetPhysicalAddress(IN:handle:[0x%0X], OUT:physicalAddress:[%01x.%01x.%01x.%01x]) HDMI_CEC_STATUS:[%s]",
+            gHandle, gPhysicalAddressBytes[3], gPhysicalAddressBytes[2], gPhysicalAddressBytes[1], gPhysicalAddressBytes[0],
+            UT_Control_GetMapString(cecError_mapTable, status));
+    }
+    else
+    {
+        UT_LOG_ERROR("HdmiCecGetPhysicalAddress failed.");
```
Comment (kanjoe24) [inline src/test_l3_hdmi_cec_driver.c:479]: shouldn't we return when getphysical adrdess fails?

**Review by kanjoe24 — CHANGES_REQUESTED** [review]
Added comments.
Also, check copilot comments and address them if relavant.

File: src/test_l3_hdmi_cec_driver.c (hunk 3 above)
Comment (KarthikeyanR470) [reply src/test_l3_hdmi_cec_driver.c]: this is end of function. so i think not required here.

File: src/test_l3_hdmi_cec_driver.c (hunk 5 above)
Comment (KarthikeyanR470) [reply src/test_l3_hdmi_cec_driver.c:479]: this is end of function. so i think not required here.

File: src/test_l3_hdmi_cec_driver.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (KarthikeyanR470) [reply src/test_l3_hdmi_cec_driver.c]: Updated

File: src/test_l3_hdmi_cec_driver.c [hunk 6]
```diff
@@ -648,7 +650,7 @@ void test_l3_hdmi_cec_hal_TransmitHdmiCecCommand(void) {
     UT_LOG_INFO("Calling HdmiCecTx(IN:handle:[0x%0X], IN:buf:[%p], IN:len:[%d], OUT:result:[])", gHandle, buf, len);
     int32_t status = HdmiCecTx(gHandle, buf, len, &result);
     UT_LOG_INFO("Result HdmiCecTx(IN:handle:[0x%0X], IN:buf:[%p], IN:len:[%d], OUT:result:[%s]) HDMI_CEC_STATUS:[%s]", gHandle, buf, len, UT_Control_GetMapString(cecError_mapTable, result)? UT_Control_GetMapString(cecError_mapTable, result):"HDMI_CEC_IO_SENT_FAILED", UT_Control_GetMapString(cecError_mapTable,status));
-    assert(status == HDMI_CEC_IO_SUCCESS || status == HDMI_CEC_IO_SENT_AND_ACKD || status == HDMI_CEC_IO_SENT_BUT_NOT_ACKD );
+    CEC_ASSERT(status == HDMI_CEC_IO_SUCCESS || status == HDMI_CEC_IO_SENT_AND_ACKD || status == HDMI_CEC_IO_SENT_BUT_NOT_ACKD );
```
[the remark this answers is not in the document]
Comment (KarthikeyanR470) [reply src/test_l3_hdmi_cec_driver.c:707]: addressed

File: src/test_l3_hdmi_cec_driver.c [hunk 7]
```diff
@@ -603,7 +629,7 @@ void test_l3_hdmi_cec_hal_TransmitHdmiCecCommand(void) {
     const char* commandName;
     int32_t expectedDataLength;
 
-    assert(sourceLogicalAddress != -1);
+    UT_ASSERT_NOT_EQUAL(sourceLogicalAddress, -1);
```
[the remark this answers is not in the document]
Comment (KarthikeyanR470) [reply src/test_l3_hdmi_cec_driver.c:655]: updated

**Review by kanjoe24 — APPROVED** [review]
Approved.

File: src/test_l3_hdmi_cec_driver.c (hunk 2 above)
Comment (KarthikeyanR470) [reply src/test_l3_hdmi_cec_driver.c:707]: updated

**Review by bhanucbp — APPROVED** [review]
ship it
